trigger:
  branches:
    include:
      - releases/*
    exclude:
      - main
      
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: $(Build.SourceBranchName).$(Rev:r)

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--property:version=$(Build.BuildNumber)'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/*.csproj'
#     includesymbols: true
#     includesource: true
#     versioningScheme: 'off'
#     buildProperties: 'version=$(Build.BuildNumber);SolutionDir=$(Build.SourcesDirectory)\;'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'